server:
  port: ${SERVER_PORT:8080}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: start-up
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  servlet:
    multipart:
      file-size-threshold: 0B
      max-file-size: ${MULTIPART_MAX_FILE_SIZE:10MB}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE:12MB}
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    root: ${LOG_LEVEL_ROOT:info}
    com.startup: ${LOG_LEVEL_APP:debug}
